# Generated by Django 5.0.3 on 2024-03-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='text',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='link',
            field=models.URLField(),
        ),
    ]
