# Generated by Django 5.0.3 on 2024-03-12 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0003_remove_text_approved_text_action_choices_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='action_choices',
            new_name='action',
        ),
    ]
