# Generated by Django 5.0.3 on 2024-03-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0004_rename_action_choices_text_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
