# Generated by Django 5.0.3 on 2024-03-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0005_alter_text_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='art',
            field=models.CharField(choices=[('Mountain', 'Mountain'), ('Medicine', 'Medicine'), ('Divination', 'Divination'), ('Physical Inspection', 'Physical Inspection'), ('Destiny', 'Destiny'), ('NA', 'N/A')], default='NA', max_length=20),
        ),
    ]
