# Generated by Django 5.0.3 on 2024-03-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0006_alter_text_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
