# Generated by Django 5.0.3 on 2024-03-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0007_alter_text_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='action',
            field=models.CharField(choices=[('0', 'N/A'), ('C', 'Create'), ('P', 'Published'), ('D', 'Delete'), ('U', 'Update')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='text',
            name='art',
            field=models.CharField(choices=[('Physical Inspection', 'Physical Inspection'), ('Divination', 'Divination'), ('Medicine', 'Medicine'), ('Mountain', 'Mountain'), ('Destiny', 'Destiny'), ('NA', 'N/A')], default='NA', max_length=20),
        ),
    ]
